### PR TITLE
Pass dragged element with the reordered event

### PR DESCRIPTION
**Pull request by jensljungblad**
@ksylvest As mentioned in #36 

Something like that?

### CODE REVIEW

**Comment by ksylvest** [comment]
@jensljungblad Looks good to me. Did you compile and test?

**Comment by jensljungblad** [comment]
I only tried it locally. Should I commit the compiled files?

**Comment by ksylvest** [comment]
@jensljungblad Yeah, that would be really helpful. You should be able to run `cake watch` to get it to compile. Then we can do a new release with this component.

**Comment by jensljungblad** [comment]
@ksylvest Done. I compiled using CoffeeScript 1.9.1, that ok?

**Comment by ksylvest** [comment]
@jensljungblad Perfect. Merging.

**Pull request merged**
